### ISSUE TITLE
``PanelBuilder.withOverride`` does not append override

### ISSUE THREAD

**Issue by urianawu** [grafana/grafana-foundation-sdk#18]
When setting the ``override`` config of the ``PanelBuilder`` classes using ``withOverride`` method, no overrides are actually appended. Looking at the compiled JS it seems to be a bug with either cog or how this method is setup:

```
    // Overrides are the options applied to specific fields overriding the defaults.
    withOverride(matcher, properties) {
        if (!this.internal.fieldConfig) {
            this.internal.fieldConfig = dashboard.defaultFieldConfigSource();
        }
        if (!this.internal.fieldConfig.overrides) {
            this.internal.fieldConfig.overrides = [];
        }
        this.internal.fieldConfig.overrides.push();
        return this;
    }
```

**Comment by K-Phoen** [comment]
Hey!

Thanks for reporting this. You're correct, it's caused by a bug in cog. I started working on a fix there: https://github.com/grafana/cog/pull/203

**Comment by urianawu** [comment]
happy new year and thanks for getting the fix out so quickly!
