### ISSUE TITLE
Unable to set panel ID using ``PanelBuilder``

### ISSUE THREAD

**Issue by urianawu** [grafana/grafana-foundation-sdk#19]
Hi! It's me again.. this issue might be related to [#18](https://github.com/grafana/grafana-foundation-sdk/issues/18) but with different symptoms.

I'm encountering a use case where I need to set the ``id`` of the panels in dashboard. However there does not seem to be a generated ``id()`` setter for some ``PanelBuilder``, specifically ``timeseries.PanelBuilder`` and ``table.PanelBuilder``. The setter is available for ``RowBuilder`` though.

Expected behavior:
```
new timeseries.PanelBuilder()
        .id(thisId)
        .tooltip(buildMultiDescTooltipOptions)
        .legend(defaultLegendOptions)
        .drawStyle(GraphDrawStyle.Line);
```

More context:

The reason why I would prefer setting the id instead of having Grafana automatically set it is because I'm provisioning alerts that gets attached to these panels and will need to add the panel ID to alerts' annotations. Setting the panel ID in code saves me from querying the Grafana Cloud via HTTP API to get it.

**Comment by K-Phoen** [comment]
Hey there!

Thanks for the report :)
[This PR](https://github.com/grafana/cog/pull/204) updates our configuration to stop excluding the `id` field from panels.

I'll push new releases on this repository today or tomorrow, to make the fix for this issue and #18 available.
