### ISSUE TITLE
Request: Change `cogvariants` package name to `variants`

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana-foundation-sdk#190]
In go/cog/variants/variants.go, we have this generated code:
```go
// Code generated - EDITING IS FUTILE. DO NOT EDIT.

package cogvariants
```

Which means that when you import the package you get code that looks like this:
```go
package main

import "github.com/grafana/grafana-foundation-sdk/go/cog/variants"

var _ = cogvariants.DataqueryConfig{}
```

In Go this isn't really idiomatic (it would normally just be `package variants`) and I found myself confused when reading some of this code. We mitigated our own confusion by doing the unnecessary aliasing so the package name would appear in our imports:
```go
import cogvariants "github.com/grafana/grafana-foundation-sdk/go/cog/variants"
```

This would be a breaking change, but I think we're early enough in the project's life that if we wanted to change the package name we can, and the simplest fix for the change is just to change an import statement. 

I haven't found other instances of this pattern in the Go code for the SDK yet.

**Comment by joeblubaugh** [comment]
I'm guessing that this actually needs to be addressed in [cog](https://github.com/grafana/cog), though?

**Comment by spinillos** [comment]
I just published a new version with the change. We still using v0.0.0 for cog since we could add breaking changes.
