### ISSUE TITLE
Missing support for dashboard annotation queries

### ISSUE THREAD

**Issue by bedaka** [grafana/grafana-foundation-sdk#229]
Hello,

when trying to add an annotation to my dashboard that is based on a LOKI query, I noticed that the current implementation of the `AnnotationQuery` does not provide a field for setting the query (or `expr` how it is called in the native Grafana JSON).

## Example
This is how the annotations look in the  expression looks in the JSON Model:
```
"annotations": {
    "list": [
      { ... },
      {
        "builtIn": 0,
        "datasource": {
          "type": "loki",
          "uid": "grafanacloud-logs"
        },
        "enable": true,
        "expr": "{job=\"service-name\", source=\"console\"} |= \"MySearchString\"|json",
        "hide": false,
        "iconColor": "blue",
        "name": "Deployments"
      }
    ]
  },
```

and this is the interface provided by the `AnnotationQuery`
```
interface AnnotationQuery {
    name: string;
    datasource: DataSourceRef;
    enable: boolean;
    hide?: boolean;
    iconColor: string;
    filter?: AnnotationPanelFilter;
    target?: AnnotationTarget;
    type?: string;
    builtIn?: number;
}

interface AnnotationTarget {
    limit: number;
    matchAny: boolean;
    tags: string[];
    type: string;
}
```

As you can see there is currently no way to provide the `expr` field from above.

## Current workaround
For now we solved this by extending the AnnotationQuery like this
`type FixedAnnotationQuery = AnnotationQuery & { expr?: string };`

Are there any plans to support this properly in the SKD soon?

Thank you

**Comment by K-Phoen** [comment]
Hey,

Thanks for reporting this, a fix was just released :)
