### ISSUE TITLE
PromQL builder open sourced from grafana?

### ISSUE THREAD

**Issue by urianawu** [grafana/grafana-foundation-sdk#23]
Hi!
One of the things that is essential when using the sdk is to build [queries and expressions](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/)(the ``expr`` field of ``DataqueryBuilder``) for prometheus metrics backed panels and alerts, and I struggled to find a good [promQL](https://prometheus.io/docs/prometheus/latest/querying/basics/) builder in Typescript that are open sourced. Since Grafana UI has a good builder tool, I wanted to ask if there's anything open sourced from Grafana?

Thanks!

**Comment by K-Phoen** [comment]
Hi!

I am not aware of any Typescript library to build Prometheus queries. I'll ask around internally :)

**Comment by botflux** [comment]
Hey, I've built a PromQL query builder [https://www.npmjs.com/package/promql-query-builder](https://www.npmjs.com/package/promql-query-builder).

**Comment by K-Phoen** [comment]
Closing this issue, since it's out of the scope of the Foundation SDK :)

**Comment by K-Phoen** [comment]
For posterity: https://github.com/grafana/promql-builder
