### ISSUE TITLE
missing data links field for panels

### ISSUE THREAD

**Issue by markspace** [grafana/grafana-foundation-sdk#352]
I wanted to add a data link to a timeseries panel using the python SDK. There is a links method for adding panel links - but nothing to add a data link.

In the end I created the panel and then set the field directly

```python
    panel = timeseries.Panel()...

    panel._internal.field_config.defaults.links = [
        {
            "title": "Drill down to this instance",
            "url": "/d/XXXX/?var-instance=${__field.labels.instance}&${__url_time_range}",
        }
    ]
```

**Comment by K-Phoen** [comment]
Thanks for reporting this :)

A [fix](https://github.com/grafana/cog/pull/634) landed in cog (the tool we use to generate this SDK) and it should be released here soon.
