### ISSUE TITLE
How to set min step of data query?

### ISSUE THREAD

**Issue by urianawu** [grafana/grafana-foundation-sdk#36]
Hello!

Some of our queries need the "min step" to be set, and from grafana JSON it looks like it'd be the `interval` field in `DataQueryBuilder` however I did not see the field. I'm suspecting this is due to the field missing in the [schema](https://grafana.com/docs/grafana/v10.2/developers/kinds/composable/prometheus/dataquery/schema-reference/), is there any way you can send out a temp fix for the SDK? Thanks!

**Comment by K-Phoen** [comment]
A fix has landed :)
