### ISSUE TITLE
Missing regex function in queryvariable builder in golang

### ISSUE THREAD

**Issue by chevech** [grafana/grafana-foundation-sdk#37]
it is available on grafana UI `v10.2.0` but it is not available to set through code https://github.com/grafana/grafana-foundation-sdk/blame/c194c2c51b5a7f5ac9f865d838411567bb2890d5/go/dashboard/queryvariable_builder_gen.go#L135

I dont understand because i can see the datamodel defined https://github.com/grafana/kind-registry/blob/4798cfda9258a1bde10217a615cddaf8cbe3547e/grafana/v10.2.x/core/dashboard/dashboard.cue#L210

how come it does not show up on on the queryvariable_builder_gen file? 🤔

**Comment by K-Phoen** [comment]
Hey!

Thanks for opening this issue. This option was excluded by mistake, I opened a PR on our codegen tool to fix that. A fix should land in this repository soon :)
