### ISSUE TITLE
[Schemas]: Missing `auto` field for dashboard.VariableModel

### ISSUE THREAD

**Issue by olehholovko-stripe** [grafana/grafana-foundation-sdk#379]
### version

11.3.x

### Missing field.

Missing `auto` field for dashboard.VariableModel

### Link to documentation.

https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#add-an-interval-variable

### Do you want to add any other information?

Hi!

Currently, it's not possible to set `auto` field for dashboard Interval variable. This is a handy default for a lot of our `interval` dashboard variable. Also, potentially unrelated, but the magic constant for the `auto` option is quite obscure and is `$__auto_interval_min_interval`, here is the part of the interval variable json
```json
      {
        "allFormat": "glob",
        "auto": true,
        "auto_count": 40,
        "auto_min": "10s",
        "current": {
          "selected": false,
          "text": "auto",
          "value": "$__auto_interval_min_interval"
        }
}
```

**Comment by K-Phoen** [comment]
Hey,

Thanks for reporting this! I started working on a fix in https://github.com/grafana/cog/pull/656 :)

**Comment by K-Phoen** [comment]
A fix just landed in this repo :)

**Comment by olehholovko-stripe** [comment]
Thank you @K-Phoen !
