### ISSUE TITLE
[Bug]: ConstantVariable not hidden

### ISSUE THREAD

**Issue by markspace** [grafana/grafana-foundation-sdk#391]
### version

11.3.x

### language

- [ ] Go
- [ ] Java
- [ ] PHP
- [x] Python
- [ ] Typescript

### Describe your bug

If you create a constant template variable with the builder dashboard.ConstantVariable, it is not hidden (the hide field is not generated). There is no hide method on this class - which makes sense as all constants should be hidden. If you upload the generated json - the template variable is displayed as a box with a name in it. If you go into edit mode and then save with no changes, the hide field is added to the json.

I have currently worked round this by patching the _internal.hide value of the ConstantVariable builder object as the underlying variable model does have the hide field.

```python
def patched_contsant_variable(name: str) -> dashboard.ConstantVariable:
    constant_variable = dashboard.ConstantVariable(name)
    constant_variable._internal.hide = VariableHide.HIDE_VARIABLE
    return constant_variable
```

### What did you expect to happen?

ConstantVariables should always have the hide field set to HIDE_VARIABLE and generate json with that setting

**Comment by markspace** [comment]
Fixed with the latest release - thanks

grafana-foundation-sdk = "1732830272!11.3.0"

**Comment by K-Phoen** [comment]
My pleasure :)
