### ISSUE TITLE
[Schemas]: Cannot specify Tags in dashboardlist Panel

### ISSUE THREAD

**Issue by chris-downs** [grafana/grafana-foundation-sdk#417]
### version

11.3.x

### Missing field.

Missing Tags setter in dashboardlist

### Link to documentation.

https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/dashboard-list/

### Do you want to add any other information?

I can see Tags defined in dashboardlist.Options but there is no setter in dashboardlist.PanelBuilder for it. I am working in Go, but I didn't see it when glancing at Java either. Am I missing something or is this getting missed during generation?

**Comment by K-Phoen** [comment]
Hey!

Thanks for reporting this. It was indeed omitted during the codegen process.
#419 fixes this, see https://github.com/grafana/grafana-foundation-sdk/blob/e35c2b6d7d759ebeea09f2d65d3a1ac25987ca87/go/dashboardlist/panel_builder_gen.go#L498-L505

**Comment by chris-downs** [comment]
Thanks for the quick fix!
