### ISSUE TITLE
Is it possible to configure value color scheme?

### ISSUE THREAD

**Issue by hallum** [grafana/grafana-foundation-sdk#44]
For a State timeline panel, I would like to set the Color Scheme in Standard Options to "From thresholds (by value)" 

I see in the SDK the types and builder for FieldColor exist, but I do not see a way to apply these to a given panel.

Does the SDK support a way to leverage the NewFieldColorBuilder for the statetimeline panel?

thx!

**Comment by spinillos** [comment]
You can use [Defaults](https://github.com/grafana/grafana-foundation-sdk/blob/v10.3.x%2Bcog-v0.0.x/go/statetimeline/panel_builder_gen.go#L329) function to pass the FieldConfig for that panel. FieldConfig contains the [Color](https://github.com/grafana/grafana-foundation-sdk/blob/v10.3.x%2Bcog-v0.0.x/go/dashboard/types_gen.go#L685) field.

Its a bit hidden and its something that we could improve :)
