### ISSUE TITLE
How to set includeAll for dashboard variables

### ISSUE THREAD

**Issue by hallum** [grafana/grafana-foundation-sdk#49]
I need to set includeAll: true for custom and query dashboard variables.  I tried setting the "All" value as selected using Current and in the Options slice, but Grafana does not perform the enumeration that happens with includeAll == true.

Is there another method to set includeAll for custom and query dashboard variables?

thx

**Comment by urianawu** [comment]
A fellow user here 😃  Are you using the latest release? I had the same issue and it was fixed here https://github.com/grafana/grafana-foundation-sdk/issues/17

**Comment by hallum** [comment]
Ahh, I can see the change on the "next" branch.  I was using the 10.3.x branch to match the version of Grafana I am using.
