### ISSUE TITLE
Table builder MarshalJSON error

### ISSUE THREAD

**Issue by hallum** [grafana/grafana-foundation-sdk#50]
I tried adding a Table to a dashboard and had the following error during the build

`json: error calling MarshalJSON for type dashboard.PanelOrRowPanel: json: error calling MarshalJSON for type common.TableAutoCellOptionsOrTableSparklineCellOptionsOrTableBarGaugeCellOptionsOrTableColoredBackgroundCellOptionsOrTableColorTextCellOptionsOrTableImageCellOptionsOrTableDataLinksCellOptionsOrTableJsonViewCellOptions: unexpected end of JSON input`

Sample Table usage which triggers the error:

`WithPanel(table.NewPanelBuilder().Title("table")).`

The cell option struct in the error was composed of pointers and the json for each field had omitempty.  I wanted to see if there additional options which are expected to create a table?

**Comment by K-Phoen** [comment]
Thanks for reporting this, I'll look into it and come back to you once I have more info :)

**Comment by K-Phoen** [comment]
A fix was released today :)
