### ISSUE TITLE
gridPos calculated incorrectly for panels collapsed in row

### ISSUE THREAD

**Issue by urianawu** [grafana/grafana-foundation-sdk#56]
Hi!

I need to create some panels that are by default collapsed so I'm using the ``.panels()`` function in ``RowBuilder`` with ``.collapsed(true)``. However the ``grisPos`` for these collapsed panels are not generated correctly.

This is the configuration of my panels:
```
    let panel = new timeseries.PanelBuilder()
        .tooltip(multiDescTooltipOptions)
        .legend(defaultLegendOptions)
        .drawStyle(GraphDrawStyle.Line)
        .lineInterpolation(interpolation)
        .fillOpacity(20)
        .showPoints(VisibilityMode.Never)
        .height(8)
        .span(12)
        .maxPerRow(2)
...

```

This is what I got in JSON:
```json
    {
      "collapsed": true,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 198
      },
      "id": 54,
      "panels": [
        {
           ...
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 55,
          "interval": "5m",
          "maxPerRow": 2,
          ....
      },
      {
          ....
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 56,
          "interval": "5m",
          "maxPerRow": 2,
         ....
      }
     ]
    }
```
Each panel take one row instead of having two panels side to side:
![Screenshot 2024-03-21 at 5 50 06 PM](https://github.com/grafana/grafana-foundation-sdk/assets/8752169/11a2a534-1d01-4759-a0a5-05e5c27fffa2)

This is only an issue with panels defined in ``RowBuilder``. Panels directly added to ``DashboardBuilder`` with ``.withPanel()`` have correct gridPos and are sitting correctly on UI.

**Comment by K-Phoen** [comment]
Hey!

Thanks for reporting this. I'm working on a fix in https://github.com/grafana/cog/pull/299, if everything goes well it should be released here sometime next week :)

**Comment by K-Phoen** [comment]
Release done!
